### ISSUE TITLE
Global scale and size of controllers

### ISSUE THREAD

**Issue by mottosso** [miquelcampos/mgear#50]
Hi @miquelcampos, first of all, great work with mGear. I'm taking it for a spin right now, and think it looks fantastic!

I ran into an issue with the default "Import Biped Guide" when scaling `local_C0_root` to small values, such as `0.1`, and then "Build From Selection" where some of the controllers scale well, but others stay at their original size.

![image](https://user-images.githubusercontent.com/2152766/29610408-fe0b9026-87f1-11e7-8320-d5d65bc85d57.png)

Maybe there is a scale parameter someplace I'm not seeing, otherwise maybe it's a bug.

**Comment by miquelcampos** [comment]
Hi Marcus,
Woah! I am super glad you trying mGear!  I am using pyblish to drive some test on mGear rigs (only validators at this point) also planing to change my pyqt module to your Qt.py :) 

Regarding your question: This happens because I don't calculate the relative size of the Icon based on the general rig size in all the controls (Also if you have any custom shape stored)
For the Control_01 component you can edit the size on the component settings tab:
![image](https://user-images.githubusercontent.com/1050212/29611478-9be6755e-8838-11e7-817e-37bf6600bc96.png)

I have to implement a better method like the other controls. This only should affect the ctl shape size but the rig should work correctly. I usally adjust this by hand and store it using the Extr. Ctl button on the component window
![image](https://user-images.githubusercontent.com/1050212/29611834-1372cda6-883a-11e7-9848-feb188568c63.png)

 I should improve it, but is not high priority in my To Do list.  I hope it is OK for you. 

I will keep the issue open, so I dont forget it .

Please keep the feedback coming :)
btw: are you in the mgear user group?

Thanks,
Miquel

**Comment by mottosso** [comment]
Thanks @miquelcampos, that *almost* did the trick. I'm still getting a few oversized items, on his head.

Here's how I set the scale attribute.

```python
for ctrl in cmds.ls():
    if cmds.objExists(ctrl + ".ctlSize"):
        cmds.setAttr(ctrl + ".ctlSize", 0.15)
```

Any ideas?

![image](https://user-images.githubusercontent.com/2152766/29613047-115535ba-87fc-11e7-80d1-5e20710662a7.png)

> btw: are you in the mgear user group?

I applied a few hours ago, not sure whether it was accepted yet. How come it's not public? I think it would simplify searching for problems and linking folks to topics without having them register first.

**Comment by miquelcampos** [comment]
I think your script solves it in part. But there is some components that doesn't expose the ctl size.  Sorry for that.

Regarding the group: ops! I thought was public readable. I just have changed the settings, now everybody can read the posts without be member. Thanks for pointing this.
For posting I am not sure if is good idea to make it public.

**Comment by mottosso** [comment]
Thanks @miquelcampos, that works for now!
