### ISSUE TITLE
Shifter:  Synoptic: IK/FK  Match  with arm_ms_2jnt_01 

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#80]
Component arm_ms_2jnt_01 does not seem to take arm length into consideration when using the maya.utils FK IK matching function. If you keep running the code a stretched IK arm becomes shorter and shorter as you match between FK and IK

**Comment by Lohult** [comment]
Hi,
It seems that in the synoptic/utils.py you matchWorldTransform is calling the target first then the source:
`matchWorldTransform(source, target)` instead in utils.py it is used as `matchWorldTransform(target, source)`
Swapping it around works although this limb "arm_ms_2jnt_01" does not seem to be compatible with the current method of matching because the wrist FK control does not influence translation, only rotation. This means that if the IK arm is stretched out, there is no way for the FK wrist to match the location of the IK _mth node.

**Comment by miquelcampos** [comment]
Thanks for the tip!  I have this issue the "in progress" column https://github.com/miquelcampos/mgear/projects/2
This means that it is scheduled for this week. Sadly, I am a little off of my goal this week. I hope next week I can tackle the issue :)

**Comment by miquelcampos** [comment]
Hi @Lohult  Finally I have checked this issue.  And yep! some of the features on "arm_ms_2jnt_01" are not supported by the IK/FK match.  
Not only the stretch, but also this component has some extra rotation/twist controls that are not supported.  
I have to invest much more time that the initially estimate to update the matching logic, in order to support this component. 
I am going to close this issue. And open a new one to implement a new matching logic with more flexibility. 
I also need to support the 3 bone legs.
